site_name: Pablo - SysAdmin Portfolio
site_url: https://pabloceda.github.io/Mis-Documentaciones/
site_description: Portfolio y blog técnico - Especialista en ASIR

# Repository info
repo_name: Pabloceda/Mis-Documentaciones
repo_url: https://github.com/Pabloceda/Mis-Documentaciones
edit_uri: edit/main/docs/

theme:
  name: material
  language: es
  
  # Paleta de colores moderna
  palette: 
    # Modo Oscuro
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
    # Modo Claro
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro

  # Tipografía moderna
  font:
    text: Inter
    code: JetBrains Mono

  # Características extra
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - announce.dismiss

# Plugins
plugins:
  - search:
      lang: es
  
  - blog:
      blog_dir: blog
      post_dir: "{blog}/posts"
      post_date_format: full
      post_url_format: "{slug}"
      authors: true
      authors_file: "{blog}/.authors.yml"
      categories: true
      categories_allowed:
        - Python
        - Redes
        - Seguridad
        - DevOps
        - Tutorial
      archive: true
      archive_name: Archivo
      archive_date_format: yyyy
      pagination: true
      pagination_per_page: 10
  
  - tags:
      tags_file: tags.md
  
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  
  - glightbox

# Extensiones de Markdown
markdown_extensions:
  # Sintaxis básica
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      
  # Admonitions
  - admonition
  - pymdownx.details
  
  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  
  # Listas y formato
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all
  
  # Contenido especial
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.critic
  
  # Emojis e iconos
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  # Tabs y contenido
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.smartsymbols

# Navegación
nav:
  - Inicio: index.md
  - Blog:
    - blog/index.md
  - Proyectos:
    - proyectos/index.md
  - Documentación:
    - documentacion/index.md
    - Python:
      - python/index.md
      - BuscaMinas: python/buscaminas.md
    - Desarrollo Web: web/index.md
    - Bases de Datos: bases-datos/index.md
    - Redes: redes/index.md
    - Seguridad: seguridad/index.md
    - Cursos: cursos/index.md
    - Certificaciones: certificaciones/index.md
  - Sobre Mí: sobre-mi.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pabloceda
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/pabloceda
      name: LinkedIn
  
  generator: false

# Copyright
copyright: >
  Copyright &copy; 2026 Pablo

# Estilos personalizados
extra_css:
  - assets/stylesheets/extra.css

# JavaScript personalizado
extra_javascript:
  - assets/javascripts/extra.js
